Fix workflow

diff --git a/.github/workflows/_get-environment.yml b/.github/workflows/_get-environment.yml
--- a/.github/workflows/_get-environment.yml
+++ b/.github/workflows/_get-environment.yml
@@ -37,6 +37,10 @@ jobs:
             refs/heads/feature/*)
               environment="development"
               ;;
+            *)
+              echo "ERROR: Invalid brunch: ${git_branch}!"
+              exit 1
+              ;;
           esac
           
           echo "environment=${environment}" >> $GITHUB_OUTPUT
